#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034

START=99
STOP=10
USE_PROCD=1

PROG=/data/mihomo/mihomo-netns-autostart.sh
SERVICE=/data/mihomo/mihomo-netns.sh

start_service() {
    rm -f /tmp/mihomo-netns-manual-stop
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param limits nofile="65535 65535"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    "$SERVICE" stop
}
